spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ecdemo?useSSL=false&useUnicode=true&characterEncoding=utf-8&character_set_server=utf8mb4
    username: root
    password: 12345678
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false