server:
  port: 8080

spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/ec_demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 16
        max-wait: 10ms

#    type: ehcache
#    ehcache:
#      config: ehcache.xml

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.cloudshiba.pubsub.entity

#logging:
#  level: info